### ISSUE TITLE
Alignment to stream-spec

### ISSUE THREAD

**Issue by rubensworks** [rdfjs/query-spec#3]
I propose to use the [stream-spec](https://github.com/rdfjs/stream-spec/) as a basis for this query spec,
for things like query results and insert/delete streams.

While a sync variant may also make sense, I do not see an immediate need for it, but I'm open for it.

**Comment by jacoscaz** [comment]
Agreed, no need for a synchronous interface for the time being.

**Comment by rubensworks** [comment]
Done in #4.
